# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hypergraph_embedding/hypergraph.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hypergraph_embedding/hypergraph.proto',
  package='hypergraph_embedding',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n%hypergraph_embedding/hypergraph.proto\x12\x14hypergraph_embedding\"#\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x65\x64ge_id\x18\x02 \x03(\t\"#\n\x04\x45\x64ge\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x03(\t\"\xa4\x02\n\nHypergraph\x12\n\n\x02id\x18\x01 \x01(\t\x12:\n\x05nodes\x18\x02 \x03(\x0b\x32+.hypergraph_embedding.Hypergraph.NodesEntry\x12:\n\x05\x65\x64ges\x18\x03 \x03(\x0b\x32+.hypergraph_embedding.Hypergraph.EdgesEntry\x1aH\n\nNodesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.hypergraph_embedding.Node:\x02\x38\x01\x1aH\n\nEdgesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.hypergraph_embedding.Edge:\x02\x38\x01')
)




_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='hypergraph_embedding.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hypergraph_embedding.Node.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edge_id', full_name='hypergraph_embedding.Node.edge_id', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=98,
)


_EDGE = _descriptor.Descriptor(
  name='Edge',
  full_name='hypergraph_embedding.Edge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hypergraph_embedding.Edge.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='hypergraph_embedding.Edge.node_id', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=135,
)


_HYPERGRAPH_NODESENTRY = _descriptor.Descriptor(
  name='NodesEntry',
  full_name='hypergraph_embedding.Hypergraph.NodesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='hypergraph_embedding.Hypergraph.NodesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='hypergraph_embedding.Hypergraph.NodesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=356,
)

_HYPERGRAPH_EDGESENTRY = _descriptor.Descriptor(
  name='EdgesEntry',
  full_name='hypergraph_embedding.Hypergraph.EdgesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='hypergraph_embedding.Hypergraph.EdgesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='hypergraph_embedding.Hypergraph.EdgesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=430,
)

_HYPERGRAPH = _descriptor.Descriptor(
  name='Hypergraph',
  full_name='hypergraph_embedding.Hypergraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hypergraph_embedding.Hypergraph.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='hypergraph_embedding.Hypergraph.nodes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edges', full_name='hypergraph_embedding.Hypergraph.edges', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_HYPERGRAPH_NODESENTRY, _HYPERGRAPH_EDGESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=430,
)

_HYPERGRAPH_NODESENTRY.fields_by_name['value'].message_type = _NODE
_HYPERGRAPH_NODESENTRY.containing_type = _HYPERGRAPH
_HYPERGRAPH_EDGESENTRY.fields_by_name['value'].message_type = _EDGE
_HYPERGRAPH_EDGESENTRY.containing_type = _HYPERGRAPH
_HYPERGRAPH.fields_by_name['nodes'].message_type = _HYPERGRAPH_NODESENTRY
_HYPERGRAPH.fields_by_name['edges'].message_type = _HYPERGRAPH_EDGESENTRY
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Edge'] = _EDGE
DESCRIPTOR.message_types_by_name['Hypergraph'] = _HYPERGRAPH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), dict(
  DESCRIPTOR = _NODE,
  __module__ = 'hypergraph_embedding.hypergraph_pb2'
  # @@protoc_insertion_point(class_scope:hypergraph_embedding.Node)
  ))
_sym_db.RegisterMessage(Node)

Edge = _reflection.GeneratedProtocolMessageType('Edge', (_message.Message,), dict(
  DESCRIPTOR = _EDGE,
  __module__ = 'hypergraph_embedding.hypergraph_pb2'
  # @@protoc_insertion_point(class_scope:hypergraph_embedding.Edge)
  ))
_sym_db.RegisterMessage(Edge)

Hypergraph = _reflection.GeneratedProtocolMessageType('Hypergraph', (_message.Message,), dict(

  NodesEntry = _reflection.GeneratedProtocolMessageType('NodesEntry', (_message.Message,), dict(
    DESCRIPTOR = _HYPERGRAPH_NODESENTRY,
    __module__ = 'hypergraph_embedding.hypergraph_pb2'
    # @@protoc_insertion_point(class_scope:hypergraph_embedding.Hypergraph.NodesEntry)
    ))
  ,

  EdgesEntry = _reflection.GeneratedProtocolMessageType('EdgesEntry', (_message.Message,), dict(
    DESCRIPTOR = _HYPERGRAPH_EDGESENTRY,
    __module__ = 'hypergraph_embedding.hypergraph_pb2'
    # @@protoc_insertion_point(class_scope:hypergraph_embedding.Hypergraph.EdgesEntry)
    ))
  ,
  DESCRIPTOR = _HYPERGRAPH,
  __module__ = 'hypergraph_embedding.hypergraph_pb2'
  # @@protoc_insertion_point(class_scope:hypergraph_embedding.Hypergraph)
  ))
_sym_db.RegisterMessage(Hypergraph)
_sym_db.RegisterMessage(Hypergraph.NodesEntry)
_sym_db.RegisterMessage(Hypergraph.EdgesEntry)


_HYPERGRAPH_NODESENTRY._options = None
_HYPERGRAPH_EDGESENTRY._options = None
# @@protoc_insertion_point(module_scope)
