# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hypergraph_embedding/hypergraph.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hypergraph_embedding/hypergraph.proto',
  package='hypergraph_embedding',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n%hypergraph_embedding/hypergraph.proto\x12\x14hypergraph_embedding\"\x16\n\x05\x45\x64ges\x12\r\n\x05\x65\x64ges\x18\x01 \x03(\x05\"\x16\n\x05Nodes\x12\r\n\x05nodes\x18\x01 \x03(\x05\"\x94\x02\n\nHypergraph\x12\x38\n\x04node\x18\x01 \x03(\x0b\x32*.hypergraph_embedding.Hypergraph.NodeEntry\x12\x38\n\x04\x65\x64ge\x18\x02 \x03(\x0b\x32*.hypergraph_embedding.Hypergraph.EdgeEntry\x1aH\n\tNodeEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.hypergraph_embedding.Edges:\x02\x38\x01\x1aH\n\tEdgeEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.hypergraph_embedding.Nodes:\x02\x38\x01')
)




_EDGES = _descriptor.Descriptor(
  name='Edges',
  full_name='hypergraph_embedding.Edges',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='edges', full_name='hypergraph_embedding.Edges.edges', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=85,
)


_NODES = _descriptor.Descriptor(
  name='Nodes',
  full_name='hypergraph_embedding.Nodes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='hypergraph_embedding.Nodes.nodes', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=109,
)


_HYPERGRAPH_NODEENTRY = _descriptor.Descriptor(
  name='NodeEntry',
  full_name='hypergraph_embedding.Hypergraph.NodeEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='hypergraph_embedding.Hypergraph.NodeEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='hypergraph_embedding.Hypergraph.NodeEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=314,
)

_HYPERGRAPH_EDGEENTRY = _descriptor.Descriptor(
  name='EdgeEntry',
  full_name='hypergraph_embedding.Hypergraph.EdgeEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='hypergraph_embedding.Hypergraph.EdgeEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='hypergraph_embedding.Hypergraph.EdgeEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=388,
)

_HYPERGRAPH = _descriptor.Descriptor(
  name='Hypergraph',
  full_name='hypergraph_embedding.Hypergraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='hypergraph_embedding.Hypergraph.node', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edge', full_name='hypergraph_embedding.Hypergraph.edge', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_HYPERGRAPH_NODEENTRY, _HYPERGRAPH_EDGEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=388,
)

_HYPERGRAPH_NODEENTRY.fields_by_name['value'].message_type = _EDGES
_HYPERGRAPH_NODEENTRY.containing_type = _HYPERGRAPH
_HYPERGRAPH_EDGEENTRY.fields_by_name['value'].message_type = _NODES
_HYPERGRAPH_EDGEENTRY.containing_type = _HYPERGRAPH
_HYPERGRAPH.fields_by_name['node'].message_type = _HYPERGRAPH_NODEENTRY
_HYPERGRAPH.fields_by_name['edge'].message_type = _HYPERGRAPH_EDGEENTRY
DESCRIPTOR.message_types_by_name['Edges'] = _EDGES
DESCRIPTOR.message_types_by_name['Nodes'] = _NODES
DESCRIPTOR.message_types_by_name['Hypergraph'] = _HYPERGRAPH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Edges = _reflection.GeneratedProtocolMessageType('Edges', (_message.Message,), dict(
  DESCRIPTOR = _EDGES,
  __module__ = 'hypergraph_embedding.hypergraph_pb2'
  # @@protoc_insertion_point(class_scope:hypergraph_embedding.Edges)
  ))
_sym_db.RegisterMessage(Edges)

Nodes = _reflection.GeneratedProtocolMessageType('Nodes', (_message.Message,), dict(
  DESCRIPTOR = _NODES,
  __module__ = 'hypergraph_embedding.hypergraph_pb2'
  # @@protoc_insertion_point(class_scope:hypergraph_embedding.Nodes)
  ))
_sym_db.RegisterMessage(Nodes)

Hypergraph = _reflection.GeneratedProtocolMessageType('Hypergraph', (_message.Message,), dict(

  NodeEntry = _reflection.GeneratedProtocolMessageType('NodeEntry', (_message.Message,), dict(
    DESCRIPTOR = _HYPERGRAPH_NODEENTRY,
    __module__ = 'hypergraph_embedding.hypergraph_pb2'
    # @@protoc_insertion_point(class_scope:hypergraph_embedding.Hypergraph.NodeEntry)
    ))
  ,

  EdgeEntry = _reflection.GeneratedProtocolMessageType('EdgeEntry', (_message.Message,), dict(
    DESCRIPTOR = _HYPERGRAPH_EDGEENTRY,
    __module__ = 'hypergraph_embedding.hypergraph_pb2'
    # @@protoc_insertion_point(class_scope:hypergraph_embedding.Hypergraph.EdgeEntry)
    ))
  ,
  DESCRIPTOR = _HYPERGRAPH,
  __module__ = 'hypergraph_embedding.hypergraph_pb2'
  # @@protoc_insertion_point(class_scope:hypergraph_embedding.Hypergraph)
  ))
_sym_db.RegisterMessage(Hypergraph)
_sym_db.RegisterMessage(Hypergraph.NodeEntry)
_sym_db.RegisterMessage(Hypergraph.EdgeEntry)


_HYPERGRAPH_NODEENTRY._options = None
_HYPERGRAPH_EDGEENTRY._options = None
# @@protoc_insertion_point(module_scope)
